# vim: set filetype=helm:
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-random-secrets
type: Opaque
data:
  DB_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
API_KEY: {{ randAlphaNum 32 | b64enc | quote }}
